proxy-providers:
  AKUN1:
    type: file
    path: "./proxy_provider/Akun/AKUN1.yaml"
    health-check:
      enable: true
      url: 'http://www.gstatic.com/generate_204'
      interval: '300'
  AKUN2:
    type: file
    path: "./proxy_provider/Akun/AKUN2.yaml"
    health-check:
      enable: true
      url: 'http://www.gstatic.com/generate_204'
      interval: '300'
  AKUN3:
    type: file
    path: "./proxy_provider/Akun/AKUN3.yaml"
    health-check:
      enable: true
      url: 'http://www.gstatic.com/generate_204'
      interval: '300'
  AKUN4:
    type: file
    path: "./proxy_provider/Akun/AKUN4.yaml"
    health-check:
      enable: true
      url: 'http://www.gstatic.com/generate_204'
      interval: '300'
  AKUN5:
    type: file
    path: "./proxy_provider/Akun/AKUN5.yaml"
    health-check:
      enable: true
      url: 'http://www.gstatic.com/generate_204'
      interval: '300'
  AKUN6:
    type: file
    path: "./proxy_provider/Akun/AKUN6.yaml"
    health-check:
      enable: true
      url: 'http://www.gstatic.com/generate_204'
      interval: '300'

proxy-groups:

- name: AKUN1
  type: select
  disable-udp: false
  use:
  - AKUN1
  url: 'http://cp.cloudflare.com/generate_204'
  interval: '300'

- name: AKUN2
  type: select
  disable-udp: false
  use:
  - AKUN2
  url: 'http://cp.cloudflare.com/generate_204'
  interval: '300'
- name: AKUN3
  type: select
  disable-udp: false
  use:
  - AKUN3
  url: 'http://cp.cloudflare.com/generate_204'
  interval: '300'
- name: AKUN4
  type: select
  disable-udp: false
  use:
  - AKUN4
  url: 'http://cp.cloudflare.com/generate_204'
  interval: '300'
- name: AKUN5
  type: select
  disable-udp: false
  use:
  - AKUN5
  url: 'http://cp.cloudflare.com/generate_204'
  interval: '300'
- name: AKUN6
  type: select
  disable-udp: false
  use:
  - AKUN6
  url: 'http://cp.cloudflare.com/generate_204'
  interval: '300'
  
- name: Relay Proxy
  type: relay
  disable-udp: false
  proxies:
  - AKUN1
  - AKUN2
  url: 'http://cp.cloudflare.com/generate_204'
  interval: '1'
  
- name: ETH1
  type: select
  interface-name: eth1
  disable-udp: false
  proxies:
  - AKUN1
  - AKUN2
  - AKUN3
  - AKUN4
  - AKUN5
  - AKUN6
  - Fallback-Akun1
  - Fallback-Akun2
  - Fallback-Akun3
  - Fallback-Akun4
  - Fallback-Akun5
  - Fallback-Akun6
  - Ping-Akun1
  - Ping-Akun2
  - Ping-Akun3
  - Ping-Akun4 
  - Ping-Akun5
  - Ping-Akun6
  - Loadbalance AKUN1
  - Loadbalance AKUN2
  - Loadbalance AKUN3
  - Loadbalance AKUN4
  - Loadbalance AKUN5
  - Loadbalance AKUN6
  - Relay Proxy
  - REJECT
  - DIRECT
  url: 'http://www.gstatic.com/generate_204'
  interval: '300'
  
- name: MACVLAN
  type: select
  interface-name: macvlan
  disable-udp: false
  proxies:
  - AKUN1
  - AKUN2
  - AKUN3
  - AKUN4
  - AKUN5
  - AKUN6
  - Fallback-Akun1
  - Fallback-Akun2
  - Fallback-Akun3
  - Fallback-Akun4
  - Fallback-Akun5
  - Fallback-Akun6
  - Ping-Akun1
  - Ping-Akun2
  - Ping-Akun3
  - Ping-Akun4 
  - Ping-Akun5
  - Ping-Akun6
  - Loadbalance AKUN1
  - Loadbalance AKUN2
  - Loadbalance AKUN3
  - Loadbalance AKUN4
  - Loadbalance AKUN5
  - Loadbalance AKUN6
  - Relay Proxy
  - REJECT
  - DIRECT
  url: 'http://www.gstatic.com/generate_204'
  interval: '300'

- name: USB0
  type: select
  interface-name: usb0
  disable-udp: false
  proxies:
  - AKUN1
  - AKUN2
  - AKUN3
  - AKUN4
  - AKUN5
  - AKUN6
  - Fallback-Akun1
  - Fallback-Akun2
  - Fallback-Akun3
  - Fallback-Akun4
  - Fallback-Akun5
  - Fallback-Akun6
  - Ping-Akun1
  - Ping-Akun2
  - Ping-Akun3
  - Ping-Akun4 
  - Ping-Akun5
  - Ping-Akun6
  - Loadbalance AKUN1
  - Loadbalance AKUN2
  - Loadbalance AKUN3
  - Loadbalance AKUN4
  - Loadbalance AKUN5
  - Loadbalance AKUN6
  - Relay Proxy
  - REJECT
  - DIRECT
  url: 'http://www.gstatic.com/generate_204'
  interval: '300'
  
- name: USB1
  type: select
  interface-name: usb1
  disable-udp: false
  proxies:
  - AKUN1
  - AKUN2
  - AKUN3
  - AKUN4
  - AKUN5
  - AKUN6
  - Fallback-Akun1
  - Fallback-Akun2
  - Fallback-Akun3
  - Fallback-Akun4
  - Fallback-Akun5
  - Fallback-Akun6
  - Ping-Akun1
  - Ping-Akun2
  - Ping-Akun3
  - Ping-Akun4 
  - Ping-Akun5
  - Ping-Akun6
  - Loadbalance AKUN1
  - Loadbalance AKUN2
  - Loadbalance AKUN3
  - Loadbalance AKUN4
  - Loadbalance AKUN5
  - Loadbalance AKUN6
  - Relay Proxy
  - REJECT
  - DIRECT
  url: 'http://www.gstatic.com/generate_204'
  interval: '300'
  
- name: Loadbalance ETH1 & MACVLAN & USB0 & USB1
  type: load-balance
  strategy: round-robin
  disable-udp: false
  proxies:
  - USB0
  - USB1
  - ETH1
  - MACVLAN
  url: 'http://www.gstatic.com/generate_204'
  interval: '1'
  
- name: Home 🌐
  type: select
  disable-udp: false
  proxies:
  - AKUN1
  - AKUN2
  - AKUN3
  - AKUN4
  - AKUN5
  - AKUN6
  - Fallback-Akun1
  - Fallback-Akun2
  - Fallback-Akun3
  - Fallback-Akun4
  - Fallback-Akun5
  - Fallback-Akun6
  - Ping-Akun1
  - Ping-Akun2
  - Ping-Akun3
  - Ping-Akun4 
  - Ping-Akun5
  - Ping-Akun6
  - Loadbalance AKUN1
  - Loadbalance AKUN2
  - Loadbalance AKUN3
  - Loadbalance AKUN4
  - Loadbalance AKUN5
  - Loadbalance AKUN6
  - Relay Proxy
  - Loadbalance ETH1 & MACVLAN & USB0 & USB1
  - ETH1
  - MACVLAN
  - USB0
  - USB1
  - REJECT
  - DIRECT
  url: 'http://cp.cloudflare.com/generate_204'
  interval: '300'

- name: Streaming 🎬
  type: select
  disable-udp: false
  proxies:
  - Home 🌐
  - AKUN1
  - AKUN2
  - AKUN3
  - AKUN4
  - AKUN5
  - AKUN6
  - Fallback-Akun1
  - Fallback-Akun2
  - Fallback-Akun3
  - Fallback-Akun4
  - Fallback-Akun5
  - Fallback-Akun6
  - Ping-Akun1
  - Ping-Akun2
  - Ping-Akun3
  - Ping-Akun4 
  - Ping-Akun5
  - Ping-Akun6
  - Loadbalance AKUN1
  - Loadbalance AKUN2
  - Loadbalance AKUN3
  - Loadbalance AKUN4
  - Loadbalance AKUN5
  - Loadbalance AKUN6
  - Relay Proxy
  - Loadbalance ETH1 & MACVLAN & USB0 & USB1
  url: 'http://cp.cloudflare.com/generate_204'
  interval: '300'

- name: Sosmed 🔔
  type: select
  disable-udp: false
  proxies:
  - Home 🌐
  - AKUN1
  - AKUN2
  - AKUN3
  - AKUN4
  - AKUN5
  - AKUN6
  - Fallback-Akun1
  - Fallback-Akun2
  - Fallback-Akun3
  - Fallback-Akun4
  - Fallback-Akun5
  - Fallback-Akun6
  - Ping-Akun1
  - Ping-Akun2
  - Ping-Akun3
  - Ping-Akun4 
  - Ping-Akun5
  - Ping-Akun6
  - Loadbalance AKUN1
  - Loadbalance AKUN2
  - Loadbalance AKUN3
  - Loadbalance AKUN4
  - Loadbalance AKUN5
  - Loadbalance AKUN6
  - Relay Proxy
  - Loadbalance ETH1 & MACVLAN & USB0 & USB1
  url: 'http://cp.cloudflare.com/generate_204'
  interval: '300'

- name: Online Shop 🛒
  type: select
  disable-udp: false
  proxies:
  - Home 🌐
  - AKUN1
  - AKUN2
  - AKUN3
  - AKUN4
  - AKUN5
  - AKUN6
  - Fallback-Akun1
  - Fallback-Akun2
  - Fallback-Akun3
  - Fallback-Akun4
  - Fallback-Akun5
  - Fallback-Akun6
  - Ping-Akun1
  - Ping-Akun2
  - Ping-Akun3
  - Ping-Akun4 
  - Ping-Akun5
  - Ping-Akun6
  - Loadbalance AKUN1
  - Loadbalance AKUN2
  - Loadbalance AKUN3
  - Loadbalance AKUN4
  - Loadbalance AKUN5
  - Loadbalance AKUN6
  - Relay Proxy
  - Loadbalance ETH1 & MACVLAN & USB0 & USB1
  url: 'http://cp.cloudflare.com/generate_204'
  interval: '300'

- name: MBanking 💲
  type: select
  disable-udp: false
  proxies:
  - Home 🌐
  - AKUN1
  - AKUN2
  - AKUN3
  - AKUN4
  - AKUN5
  - AKUN6
  - Fallback-Akun1
  - Fallback-Akun2
  - Fallback-Akun3
  - Fallback-Akun4
  - Fallback-Akun5
  - Fallback-Akun6
  - Ping-Akun1
  - Ping-Akun2
  - Ping-Akun3
  - Ping-Akun4 
  - Ping-Akun5
  - Ping-Akun6
  - Loadbalance AKUN1
  - Loadbalance AKUN2
  - Loadbalance AKUN3
  - Loadbalance AKUN4
  - Loadbalance AKUN5
  - Loadbalance AKUN6
  - Relay Proxy
  - Loadbalance ETH1 & MACVLAN & USB0 & USB1
  url: 'http://cp.cloudflare.com/generate_204'
  interval: '300'

- name: Games 🎮
  type: select
  disable-udp: false
  proxies:
  - Home 🌐
  - AKUN1
  - AKUN2
  - AKUN3
  - AKUN4
  - AKUN5
  - AKUN6
  - Fallback-Akun1
  - Fallback-Akun2
  - Fallback-Akun3
  - Fallback-Akun4
  - Fallback-Akun5
  - Fallback-Akun6
  - Ping-Akun1
  - Ping-Akun2
  - Ping-Akun3
  - Ping-Akun4 
  - Ping-Akun5
  - Ping-Akun6
  - Loadbalance AKUN1
  - Loadbalance AKUN2
  - Loadbalance AKUN3
  - Loadbalance AKUN4
  - Loadbalance AKUN5
  - Loadbalance AKUN6
  - Relay Proxy
  - Loadbalance ETH1 & MACVLAN & USB0 & USB1
  url: 'http://cp.cloudflare.com/generate_204'
  interval: '300'

- name: WHATSAPP ONLY 📞
  type: select
  disable-udp: false
  proxies:
  - Home 🌐
  - AKUN1
  - AKUN2
  - AKUN3
  - AKUN4
  - AKUN5
  - AKUN6
  - Fallback-Akun1
  - Fallback-Akun2
  - Fallback-Akun3
  - Fallback-Akun4
  - Fallback-Akun5
  - Fallback-Akun6
  - Ping-Akun1
  - Ping-Akun2
  - Ping-Akun3
  - Ping-Akun4 
  - Ping-Akun5
  - Ping-Akun6
  - Loadbalance AKUN1
  - Loadbalance AKUN2
  - Loadbalance AKUN3
  - Loadbalance AKUN4
  - Loadbalance AKUN5
  - Loadbalance AKUN6
  - Relay Proxy
  - Loadbalance ETH1 & MACVLAN & USB0 & USB1
  - DIRECT
  url: 'http://cp.cloudflare.com/generate_204'
  interval: '300'
#------------++-----++--ETC--++----++-------------#
- name: Fallback-Akun1
  type: fallback
  disable-udp: false
  use:
  - AKUN1
  url: 'http://www.gstatic.com/generate_204'
  interval: '1'
  tolerance: '1'
- name: Fallback-Akun2
  type: fallback
  disable-udp: false
  use:
  - AKUN2
  url: 'http://www.gstatic.com/generate_204'
  interval: '1'
  tolerance: '1'
- name: Fallback-Akun3
  type: fallback
  disable-udp: false
  use:
  - AKUN3
  url: 'http://www.gstatic.com/generate_204'
  interval: '1'
  tolerance: '1'
- name: Fallback-Akun4
  type: fallback
  disable-udp: false
  use:
  - AKUN4
  url: 'http://www.gstatic.com/generate_204'
  interval: '1'
  tolerance: '1'
- name: Fallback-Akun5
  type: fallback
  disable-udp: false
  use:
  - AKUN5
  url: 'http://www.gstatic.com/generate_204'
  interval: '1'
  tolerance: '1'
- name: Fallback-Akun6
  type: fallback
  disable-udp: false
  use:
  - AKUN6
  url: 'http://www.gstatic.com/generate_204'
  interval: '1'
  tolerance: '1'
#-------------------------------------------------#
- name: Ping-Akun1
  type: url-test
  disable-udp: false
  use:
  - AKUN1
  url: 'http://www.gstatic.com/generate_204'
  interval: '1'
  tolerance: '1'
- name: Ping-Akun2
  type: url-test
  disable-udp: false
  use:
  - AKUN2
  url: 'http://www.gstatic.com/generate_204'
  interval: '1'
  tolerance: '1'
- name: Ping-Akun3
  type: url-test
  disable-udp: false
  use:
  - AKUN3
  url: 'http://www.gstatic.com/generate_204'
  interval: '1'
  tolerance: '1'
- name: Ping-Akun4
  type: url-test
  disable-udp: false
  use:
  - AKUN4
  url: 'http://www.gstatic.com/generate_204'
  interval: '1'
  tolerance: '1'
- name: Ping-Akun5
  type: url-test
  disable-udp: false
  use:
  - AKUN5
  url: 'http://www.gstatic.com/generate_204'
  interval: '1'
  tolerance: '1'
- name: Ping-Akun6
  type: url-test
  disable-udp: false
  use:
  - AKUN6
  url: 'http://www.gstatic.com/generate_204'
  interval: '1'
  tolerance: '1'
#-------------------------------------------------#
- name: Loadbalance AKUN1
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - AKUN1
  url: 'http://www.gstatic.com/generate_204'
  interval: '1'
  tolerance: '1'
- name: Loadbalance AKUN2
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - AKUN2
  url: 'http://www.gstatic.com/generate_204'
  interval: '1'
  tolerance: '1'
- name: Loadbalance AKUN3
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - AKUN3
  url: 'http://www.gstatic.com/generate_204'
  interval: '1'
  tolerance: '1'
- name: Loadbalance AKUN4
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - AKUN4
  url: 'http://www.gstatic.com/generate_204'
  interval: '1'
  tolerance: '1'
- name: Loadbalance AKUN5
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - AKUN5
  url: 'http://www.gstatic.com/generate_204'
  interval: '1'
  tolerance: '1'
- name: Loadbalance AKUN6
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - AKUN6
  url: 'http://www.gstatic.com/generate_204'
  interval: '1'
  tolerance: '1'

#-------------------------------------------------#
- name: BLOCK ADS
  type: select
  disable-udp: false
  proxies:
  - REJECT
  - Home 🌐
  url: 'http://www.gstatic.com/generate_204'
  interval: '300'
#-------------------------------------------------#
rule-providers:
  Gamemaster:
    type: file
    behavior: classical
    path: ./rule_provider/rule-port-game.yaml
  Sosmedmaster:
    type: file
    behavior: classical
    path: ./rule_provider/rule-port-sosmed.yaml
  Streammaster:
    type: file
    behavior: classical
    path: ./rule_provider/rule-port-stream.yaml
  Olshopmaster:
    type: file
    behavior: classical
    path: ./rule_provider/rule-port-olshop.yaml
  Bankmaster:
    type: file
    behavior: classical
    path: ./rule_provider/rule-port-bank.yaml
  Whatsappmaster:
    type: file
    behavior: classical
    path: ./rule_provider/rule-port-whatsapp.yaml
  rule_BlockAds:
    type: file
    behavior: classical
    path: ./rule_provider/rule-myads.yaml
     
rules:
- RULE-SET,rule_BlockAds,BLOCK ADS
- RULE-SET,Gamemaster,Games 🎮
- RULE-SET,Sosmedmaster,Sosmed 🔔
- RULE-SET,Streammaster,Streaming 🎬
- RULE-SET,Olshopmaster,Online Shop 🛒
- RULE-SET,Bankmaster,MBanking 💲
- RULE-SET,Whatsappmaster,WHATSAPP ONLY 📞
- MATCH,Home 🌐
